version: '3.4'

services:

  # Rabbit MQ
  rabbit:
    image: rabbitmq:3.6-management
    ports:
      - "5672:5672"
      - "15672:15672"
    container_name: rabbit
  
  # SQL Server for Linux
  sqlserver:
    image: sqlserver
    build:
      context: ./Database
      dockerfile: Dockerfile
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Zaq123#!
    container_name: sqlserver

  # Catalog Microservice
  ecommerce.catalog.api:
    image: ecommerce/catalog.api
    build:
      context: .
      dockerfile: Services/ECommerce.Catalog.Api/Dockerfile
    environment:      
      ConnectionString: ${SQL_SERVER_CS}Database=ECommerce.Products      
      RabbitHost: rabbit
    ports:
      - "8085:80"
    depends_on: 
      - rabbit
      - sqlserver

  # Customers Microservice
  ecommerce.customers.api:
    image: ecommerce/customers.api
    build:
      context: .
      dockerfile: Services/ECommerce.Customers.Api/Dockerfile
    environment:
      ConnectionString: ${SQL_SERVER_CS}Database=ECommerce.Customers
      RabbitHost: rabbit
    ports:
      - "8082:80"
    depends_on: 
      - rabbit
      - sqlserver

# Logging Microservice
  ecommerce.logging.host:
    image: ecommerce/logging.host
    build:
      context: .
      dockerfile: Services/ECommerce.Logging.Host/Dockerfile
    environment:
      RabbitHost: rabbit
    depends_on: 
      - rabbit

  # Payment Microservice
  ecommerce.payment.host:
    image: ecommerce/payment.host
    build:
      context: .
      dockerfile: Services/ECommerce.Payment.Host/Dockerfile
    environment:
      RabbitHost: rabbit
    depends_on: 
      - rabbit

# Reporting Microservice
  ecommerce.reporting.api:
    image: ecommerce/reporting.api
    build:
      context: .
      dockerfile: Services/ECommerce.Reporting.Api/Dockerfile
    environment:
      ConnectionString: ${SQL_SERVER_CS}Database=ECommerce.Reporting
      RabbitHost: rabbit
      CustomersServiceHost: ecommerce.customers.api
    ports:
      - "8084:80"
    depends_on: 
      - rabbit
      - sqlserver

# Sales Microservice
  ecommerce.sales.api:
    image: ecommerce/sales.api
    build:
      context: .
      dockerfile: Services/ECommerce.Sales.Api/Dockerfile
    environment:
      ConnectionString: ${SQL_SERVER_CS}Database=ECommerce.Sales
      RabbitHost: rabbit
      CustomersServiceHost: ecommerce.customers.api
      CatalogServiceHost: ecommerce.catalog.api
    ports:
      - "8083:80"
    depends_on: 
      - rabbit
      - sqlserver

  # Shipping Microservice
  ecommerce.shipping.host:
    image: ecommerce/shipping.host
    build:
      context: .
      dockerfile: Services/ECommerce.Shipping.Host/Dockerfile
    environment:
      RabbitHost: rabbit
    depends_on: 
      - rabbit


  ecommerce.webapp:
    image: ecommerce/webapp
    build:
      context: .
      dockerfile: Web/ECommerce.WebApp/Dockerfile
    depends_on: 
      - ecommerce.catalog.api
      - ecommerce.customers.api
      - ecommerce.reporting.api
      - ecommerce.sales.api

