version: '3'
services:

  # Rabbit MQ
  rabbit:
    image: rabbitmq:3.6-management
    ports:
      - "5672:5672"
      - "15672:15672"
    container_name: rabbit
  
  # SQL Server for Linux
  sqlserver:
    image: sqlserver
    build:
      context: ./Database
      dockerfile: Dockerfile
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Zaq123#!
    container_name: sqlserver
  
  # Catalog Microservice
  catalog-api:
    build: ./Services/ECommerce.Catalog.Api
    image: ecommerce/catalog-api
    environment:
      - ConnectionString=Server=sqlserver;User=sa;Password=Zaq123#!;Database=ECommerce.Products
      - RabbitHost=rabbit
    ports:
    - "8081:80"
    depends_on: 
    - rabbit
    - sqlserver
    deploy:
      replicas: 2
    hostname: catalog-api
    container_name: catalog-api

  # Customers Microservice
  customers-api:
    build: ./Services/ECommerce.Customers.Api
    image: ecommerce/customers-api
    environment:
      - ConnectionString=Server=sqlserver;User=sa;Password=Zaq123#!;Database=ECommerce.Customers
      - RabbitHost=rabbit
    ports:
    - "8082:80"
    depends_on: 
    - rabbit
    - sqlserver
    deploy:
      replicas: 2
    hostname: customers-api
    container_name: customers-api

  # Sales Microservice
  sales-api:
    build: ./Services/ECommerce.Sales.Api
    image: ecommerce/sales-api
    environment:
      - ConnectionString=Server=sqlserver;User=sa;Password=Zaq123#!;Database=ECommerce.Sales
      - RabbitHost=rabbit
      - CustomersServiceHost=customers-api
      - CatalogServiceHost=catalog-api
    ports:
    - "8083:80"
    depends_on: 
    - rabbit
    - sqlserver
    hostname: sales-api
    container_name: sales-api

  # Payment Microservice
  payment-host:
    build: ./Services/ECommerce.Payment.Host
    image: ecommerce/payment-host
    environment:
      - RabbitHost=rabbit
    depends_on: 
    - rabbit
    hostname: payment-host
    container_name: payment-host

  # Shipping Microservice
  shipping-host:
    build: ./Services/ECommerce.Shipping.Host
    image: ecommerce/shipping-host
    environment:
      - RabbitHost=rabbit
    depends_on: 
    - rabbit
    hostname: shipping-host
    container_name: shipping-host

# Reporting Microservice
  reporting-api:
    build: ./Services/ECommerce.Reporting.Api
    image: ecommerce/reporting-api
    environment:
      - ConnectionString=Server=sqlserver;User=sa;Password=Zaq123#!;Database=ECommerce.Reporting
      - RabbitHost=rabbit
      - CustomersServiceHost=customers-api
    ports:
    - "8084:80"
    depends_on: 
    - rabbit
    - sqlserver
    hostname: reporting-host
    container_name: reporting-host

# Logging Microservice
  logging-host:
    build: ./Services/ECommerce.Logging.Host
    image: ecommerce/logging-host
    environment:
      - RabbitHost=rabbit
    depends_on: 
    - rabbit
    hostname: logging-host
    container_name: logging-host
